apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qtlb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-qtlb@sha256:d25cf41497145a46a5373a81ab816157f8288124ac4332499d82d8bb1da458e6
        name: my-nodejs
        resources: {}
status: {}
